# Generated by Django 5.0.2 on 2024-05-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='static/image/333.jpg', null=True, upload_to='static\\image'),
        ),
    ]
