# Generated by Django 5.0.2 on 2024-05-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hit',
            field=models.BooleanField(default=False),
        ),
    ]
